### ISSUE TITLE
error example

### ISSUE THREAD

**Issue by sp00ck** [sp4ke/howto#3]
`$howto 'filter dicts' -t python`

Traceback (most recent call last):
  File "/home/user/.local/bin/howto", line 5, in <module>
    from howto.howto import cli_run
  File "/home/user/.local/lib/python3.8/site-packages/howto/howto.py", line 71
    print result
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(result)?

**Comment by blob42** [comment]
Hi, 

The error is fixed and the script executes without errors but stackexchange changed the API rules, so in many situations no results will be returned. 

If I had time I would build this around a scrapper that bypasses the API rules since I think they are unethical. StackExchange network hoarded human knowledge for free and now control it's access and resell it ...

I do not support anymore any platform that locks content behind API keys like SO or Github so I will archive this script. Feel free to fork and adapt.
